# 如果需要在ARM架构上运行，可以将第一个 FROM 指令注释，然后将第二个 FROM 指定取消注释
FROM python:3.7.12-slim
#FROM arm64v8/python:3.7.12-slim  # For ARM

ARG EXTRA_TOOLS="gnupg curl wget jq vim-tiny net-tools procps python3-dev default-libmysqlclient-dev locales inotify-tools gcc subversion git telnet iputils-ping vim openssh-client"

RUN set -ex && cd / \
    && apt-get update \
    && apt-get install -y --no-install-recommends $EXTRA_TOOLS \
    && apt-get update \
    && apt-get install -y mariadb-client \
    && apt-get clean \
    && echo "LC_ALL=zh_CN.UTF-8" >> /etc/environment \
    && echo "zh_CN.UTF-8 UTF-8" > /etc/locale.gen \
    && echo "LANG=zh_CN.UTF-8" > /etc/locale.conf \
    && locale-gen \
    && ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime \
    && rm -rf /var/cache/apt/* /root/.cache

WORKDIR /var/www/django/codedog

COPY . .

# 如果访问官方pypi源（files.pythonhosted.org）超时或访问失败，
# 可以将下面第一个RUN命令注释，然后将第二个RUN命令取消注释，配置腾讯云pypi源进行下载
RUN mkdir -p log/ && \
    pip install -U setuptools pip && \
    pip install -r requirements.txt

# RUN mkdir -p log/ && \
#     mkdir ~/.pip/ && echo "[global]\nindex-url = https://mirrors.cloud.tencent.com/pypi/simple" >> ~/.pip/pip.conf && \
#     pip install -U setuptools pip && \
#     pip install -r requirements.txt