# Generated by Django 3.1.12 on 2022-03-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codelint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecomment',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='issuerefer',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='invalidissue',
            name='issue',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codelint.issue', verbose_name='关联issue'),
        ),
        migrations.AlterField(
            model_name='wontfixissue',
            name='issue',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codelint.issue', verbose_name='关联issue'),
        ),
    ]
