import { t } from '@src/i18n/i18next';

export const SCM_PLATFORM_ENUM = {
  TGIT: 1,
  TGITSAAS: 2,
  CODING: 3,
  GITHUB: 4,
  GITEE: 5,
  GITLAB: 6,
};

export const SCM_PLATFORM = {
  [SCM_PLATFORM_ENUM.TGIT]: t('工蜂内网'),
  [SCM_PLATFORM_ENUM.TGITSAAS]: t('腾讯工蜂'),
  [SCM_PLATFORM_ENUM.CODING]: t('Coding'),
  [SCM_PLATFORM_ENUM.GITHUB]: t('GitHub'),
  [SCM_PLATFORM_ENUM.GITEE]: t('Gitee'),
  [SCM_PLATFORM_ENUM.GITLAB]: t('GitLab'),
};

export const SCM_PLATFORM_OPTIONS = [{
  label: SCM_PLATFORM[SCM_PLATFORM_ENUM.TGITSAAS],
  value: SCM_PLATFORM_ENUM.TGITSAAS,
}, {
  label: SCM_PLATFORM[SCM_PLATFORM_ENUM.CODING],
  value: SCM_PLATFORM_ENUM.CODING,
}, {
  label: SCM_PLATFORM[SCM_PLATFORM_ENUM.GITHUB],
  value: SCM_PLATFORM_ENUM.GITHUB,
}, {
  label: SCM_PLATFORM[SCM_PLATFORM_ENUM.GITEE],
  value: SCM_PLATFORM_ENUM.GITEE,
}, {
  label: SCM_PLATFORM[SCM_PLATFORM_ENUM.GITLAB],
  value: SCM_PLATFORM_ENUM.GITLAB,
}];