# .cnb.yml
"**": # 触发的分支名，默认所有分支，按需修改
  push: # push触发，也可以用merge_request等触发
    - stages:
      # 代码分析
      - name: TCA
        image: tencentcom/tca-plugin:latest
        settings:
          block: false
