# .cnb.yml
"**": # 触发的分支名，默认所有分支，按需修改
  push: # push触发，也可以用merge_request等触发
    - docker:
        # 声明缓存目录，/data/tca_cache/tools 为TCA 工具存储目录
        volumes:
          - /data/tca_cache/tools:copy-on-write
    - stages:
      # 代码分析
      - name: TCA
        image: tencentcom/tca-plugin:latest
        settings:
          block: false
