# Generated by Django 3.1.12 on 2022-04-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeproj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanschemetemplate',
            name='need_compile',
            field=models.BooleanField(default=False, help_text='是否依赖编译'),
        ),
    ]
