# -*- coding: utf-8 -*-
#  Copyright (c) 2021-2024 THL A29 Limited
#  #
#  This source code file is made available under MIT License
#  See LICENSE for details
#  ==============================================================================
# Generated by Django 3.1.14 on 2022-08-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeproj', '0007_auto_20220617_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproject',
            name='project_key',
            field=models.CharField(blank=True, help_text='项目Key值', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseproject',
            name='scan_path',
            field=models.CharField(blank=True, help_text='扫描路径', max_length=512, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='baseproject',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='baseproject',
            index_together={('repo', 'scan_scheme', 'branch')},
        ),
    ]
