# Generated by Django 3.1.14 on 2024-06-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeproj', '0008_auto_20220803_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproject',
            name='status',
            field=models.IntegerField(choices=[(1, '活跃'), (2, '失活'), (3, '归档中'), (4, '已归档未清理'), (5, '已归档')], default=1, verbose_name='项目状态'),
        ),
    ]
