CREATE DATABASE IF NOT EXISTS codedog_main CHARACTER SET UTF8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS codedog_analysis CHARACTER SET UTF8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS codedog_file CHARACTER SET UTF8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS codedog_login CHARACTER SET UTF8mb4 COLLATE utf8mb4_general_ci;