export default {
  SET_LAYOUT_COMPLETED: 'SET_LAYOUT_COMPLETED',
  SET_PROJECT_COMPLETED: 'SET_PROJECT_COMPLETED',
  SET_USERINFO: 'SET_USERINFO',
  SET_PUPPYINFO: 'SET_PUPPYINFO',
  SET_ENTERPRISE: 'SET_ENTERPRISE',
  SET_ORG: 'SET_ORG',
};
