export default {
  LOG_LEVEL: 'LOG_LEVEL',
  MICRO_FRONTEND_API: 'MICRO_FRONTEND_API',
  MICRO_FRONTEND_API_LIST: 'MICRO_FRONTEND_API_LIST',
  MICRO_FRONTEND_SETTING_API: 'MICRO_FRONTEND_SETTING_API',
  MICRO_VERSION_INTERVAL: 'MICRO_VERSION_INTERVAL',
  MICRO_VERSION_ENABLED: 'MICRO_VERSION_ENABLED',
  MICRO_THEME_MODS: 'MICRO_THEME_MODS',
};

export const DEFAULT_MICRO_FRONTEND_API = '/static/micro-frontend/configs/latest/';

export const DEFAULT_MICRO_FRONTEND_SETTING_API = '/static/micro-frontend/settings/';

export const DEFAULT_MICRO_VERSION_INTERVAL = 10 * 60 * 1000; // 10min

export const DEFAULT_MICRO_THEME_MODS = 'light,dark';
