# Generated by Django 3.1.12 on 2022-03-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedoguser',
            name='latest_login_time',
            field=models.DateTimeField(blank=True, help_text='最近一次登录时间', null=True),
        ),
        migrations.AddField(
            model_name='organizationpermissionapply',
            name='remark',
            field=models.CharField(blank=True, help_text='备注，用于管理员审批进行的额外备注', max_length=255, null=True),
        ),
    ]
