# Generated by Django 3.1.14 on 2024-06-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_auto_20220608_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scmoauthsetting',
            name='client_secret',
            field=models.CharField(max_length=512, verbose_name='客户端密码'),
        ),
        migrations.AlterField(
            model_name='scmoauthsetting',
            name='redirect_uri',
            field=models.CharField(max_length=128, verbose_name='回调地址'),
        ),
    ]
