#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2021-2024 THL A29 Limited
#
# This source code file is made available under MIT License
# See LICENSE for details
# ==============================================================================
# Generated by Django 3.1.12 on 2021-11-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='app/type，小写字母', max_length=200, unique=True)),
                ('bucket', models.CharField(db_index=True, help_text='COS bucket', max_length=40)),
                ('creator', models.CharField(help_text='创建人', max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('expired', models.IntegerField(default=7, help_text='该单元下文件保存期限')),
                ('ext_fields', models.JSONField(blank=True, help_text='扩展字段', null=True)),
                ('other_permission', models.CharField(
                    choices=[('', '没有权限'), ('r', '只读权限'), ('rw', '读写权限')],
                    default='', help_text='其他用户是否有可写权限', max_length=2)),
            ],
            options={
                'db_table': 't_app_unit',
            },
        ),
    ]
