{{- if .Values.metrics.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "tca.fullname" . }}-main-server
spec:
  selector:
    matchLabels:
      k8s-app: {{ template "tca.fullname" . }}-main-server
  endpoints:
    - port: http
      path: /prometheus/metrics
      interval: 30s
    - port: http
      path: api/nodes/nodestate/metrics/
      interval: 1m
{{- end }}