# Generated by Django 3.1.12 on 2022-03-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodemgr', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='archived',
            field=models.BooleanField(blank=True, null=True, verbose_name='标记job是否已完成归档'),
        ),
        migrations.AddField(
            model_name='job',
            name='closing_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始入库时间'),
        ),
        migrations.CreateModel(
            name='KillingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killed_time', models.DateTimeField(blank=True, null=True, verbose_name='终止时间')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodemgr.node', verbose_name='执行节点')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.task', verbose_name='Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskProcessNodeQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodemgr.node')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.task')),
                ('task_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.taskprocessrelation')),
            ],
            options={
                'index_together': {('node', 'task_process')},
            },
        ),
    ]
