# -*- coding: utf-8 -*-
#  Copyright (c) 2021-2024 THL A29 Limited
#  #
#  This source code file is made available under MIT License
#  See LICENSE for details
#  ==============================================================================
# Generated by Django 3.1.14 on 2022-05-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20220309_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprocessnodequeue',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
