export const SET_REPOS = 'SET_REPOS';

export const SET_CUR_REPO = 'SET_CUR_REPO';

export const SET_CUR_REPO_MEMBER = 'SET_CUR_REPO_MEMBER';

export const SET_PROJECT_MEMBER = 'SET_PROJECT_MEMBER';

export const SET_REPOS_LOADING = 'SET_REPOS_LOADING';
